### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gagansidhugs** [zws-im/website#160]
![image](https://user-images.githubusercontent.com/72646682/95649384-d6fdef80-0afa-11eb-99aa-7a407dae4310.png)

We are running the script on path abc.com/src/ Please help us why it is not working

**Comment by pizzafox** [comment]
What is the error message?

**Comment by gagansidhugs** [comment]
![image](https://user-images.githubusercontent.com/72646682/95650233-f0556a80-0aff-11eb-8a7a-43bef70fad83.png)

**Comment by pizzafox** [comment]
I'm unable to reproduce, are you sure you are building the site with Parcel?

**Comment by gagansidhugs** [comment]
we are on PHP server

**Comment by pizzafox** [comment]
You still need to run the build script on the site or nothing will work.

**Comment by gagansidhugs** [comment]
I placed zws-master on root path as it is, but it is not working
Please help me to get this run

**Comment by pizzafox** [comment]
You can't do that, you need to run the build script.

**Comment by gagansidhugs** [comment]
Please share tutorial how to run the build script?

**Comment by pizzafox** [comment]
```sh
yarn build
```
