### ISSUE TITLE
Website fails when using uBlock Chrome Extension

### ISSUE THREAD

**Issue by karlhorky** [zws-im/website#327]
If users have the uBlock Chrome extension, the shortener website fails with an error that is not visible to users (but you can see it in the console, as seen below)

![Screen Shot 2021-03-01 at 21 16 39](https://user-images.githubusercontent.com/1935696/109553711-a4698900-7ad3-11eb-95e7-af00c16d0c7a.png)

**Comment by pizzafox** [comment]
Looks like maybe the Sentry SDK is getting blocked? Will investigate.

**Comment by karlhorky** [comment]
Great, thanks for digging in and the fix!
